### ISSUE TITLE
🐛 Login error when session has expired 

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/member-page#951]
Investigate why this error occurs and prevent it from happening.

![Image](https://user-images.githubusercontent.com/26229521/221382821-aab5b27f-6878-4dd1-85aa-99846fc51332.png)

**Comment by danieladugyan** [comment]
```bash
{
  error: [Function: Error] {
    stackTraceLimit: 10,
    prepareStackTrace: undefined
  }
}
[next-auth][error][OAUTH_CALLBACK_ERROR]
https://next-auth.js.org/errors#oauth_callback_error state mismatch, expected AdTh_iVtNxIvcfwEHxB9AaAamsqxl8lgaT1rXJtRkW4, got: RgDZwNvcky-7PpXqUY3128qcaJBOUWNiCsp20d9wlls {
  error: RPError: state mismatch, expected AdTh_iVtNxIvcfwEHxB9AaAamsqxl8lgaT1rXJtRkW4, got: RgDZwNvcky-7PpXqUY3128qcaJBOUWNiCsp20d9wlls
      at Client.callback (/project/app/node_modules/openid-client/lib/client.js:399:13)
      at oAuthCallback (/project/app/node_modules/next-auth/core/lib/oauth/callback.js:129:29)
      at async Object.callback (/project/app/node_modules/next-auth/core/routes/callback.js:52:11)
      at async AuthHandler (/project/app/node_modules/next-auth/core/index.js:201:28)
      at async NextAuthHandler (/project/app/node_modules/next-auth/next/index.js:24:19)
      at async /project/app/node_modules/next-auth/next/index.js:60:32
      at async Object.apiResolver (/project/app/node_modules/next/dist/server/api-utils/node.js:366:9)
      at async NextNodeServer.runApi (/project/app/node_modules/next/dist/server/next-server.js:481:9)
      at async Object.fn (/project/app/node_modules/next/dist/server/next-server.js:741:37)
      at async Router.execute (/project/app/node_modules/next/dist/server/router.js:252:36) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'keycloak',
  message: 'state mismatch, expected AdTh_iVtNxIvcfwEHxB9AaAamsqxl8lgaT1rXJtRkW4, got: RgDZwNvcky-7PpXqUY3128qcaJBOUWNiCsp20d9wlls'
}
```
